// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riqwkshrcydyemgpdbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcXdrc2hyY3lkeWVtZ3BkYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjAzMTQsImV4cCI6MjA2NzYzNjMxNH0.ln2B4CuLdFEDV1uObacx5APsdAfJVRNwMwzdr1eN3ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});